- module/cmd/gravity/cmd/root.go
originally made the PR against here by mistake: https://github.com/althea-net/cosmos-gravity-bridge/pull/366
same issue was present [in gaia](https://github.com/cosmos/gaia/pull/884) where the `keys parse` command was hanging
> fix keys parse bug

- module/x/gravity/types/msgs.go
- orchestrator/test_runner/src/invalid_events.rs
Someone sent a deposit to an Ethereum address on the live chain, since
the MsgSendToEth contains a freeform string there are lots of possible
ways it can be invalid.
The oracle component of the orchestrator has the goal of detecting
invalid deposit conditions and replacing them with an indication to the
Gravity Bridge module that this deposit should go into the community
pool. This keeps the oracle moving and prevents one bad deposit from
halting the bridge.
Sadly due to a significant oversight in the creation of the test the
invalid events test was merged with it's invalid deposits section
disabled. This patch restores it, corrects the regression that snuck
in and adds a new test case specific to what failed in production.
>  Correct invalid deposits test 

- tests/all-up-test.sh
- tests/build-container.sh
- tests/container-scripts/reload-code.sh
- tests/start-chains.sh
**Problem:**
Running bash tests/all-up-test.sh on a Mac with Apple M1 Max processor. Getting error message that eth image can not be found and then failing setup.
```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
**Solution:**
There are 3 bash scripts that need to be updated: 
- tests/all-up-test.sh
- tests/build-container.sh
- tests/start-chains.sh
In each of these scripts I put an if branch on if Mac OS and M1 processor then append --platform=linux/amd64 to docker run. Linux users should see no change with this PR
**Additional findings:** 
There is a "Docker not found" error when running ./start-chains.sh
```
/usr/bin/which: no docker in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin:/usr/local/go/bin)
```
It seems like …
> Fix Mac M1 build

- module/cmd/gravity/cmd/migrate.go
- module/cmd/gravity/cmd/root.go
Copied the genesis migration command from genutil and reworked it to call the ibc v1 -> v2 migration code
> Add `gravity ibc-migrate` command to edit ibc genesis state

- orchestrator/gbt/src/default-config.toml
- orchestrator/gbt/src/main.rs
- orchestrator/gbt/src/relayer.rs
- orchestrator/gravity_utils/src/error.rs
- orchestrator/gravity_utils/src/types/config.rs
- orchestrator/orchestrator/src/main_loop.rs
- orchestrator/relayer/src/batch_relaying.rs
- orchestrator/relayer/src/logic_call_relaying.rs
- orchestrator/relayer/src/main_loop.rs
- orchestrator/relayer/src/valset_relaying.rs
- orchestrator/test_runner/src/pause_bridge.rs
- orchestrator/test_runner/src/unhalt_bridge.rs
- orchestrator/test_runner/src/utils.rs
This is the first in a sequence of patches focused on relaying improvements.
The primary goal of this change is to make it safe for a user to run the
relayer with the default settings without valset relaying exhausting all
their funds.
Previously there where two sets of validator set relaying behavior, one
where every valset was relayed and one where only profitable valsets
where relayed.
Relaying every valset is extremely wasteful in terms of gas and isn't
good default behavior for an altruistic user. Relaying only profitable
valsets is a valid choice, but will not keep the chain running correctly
if there are no rewards or the reward is too low.
This new default state, defined by having both relay_every_valset and
valset_relay_market as false in the config. Will only relay validator …
> Add relay_every_valset option

- orchestrator/test_runner/src/happy_path.rs
- orchestrator/test_runner/src/main.rs
- orchestrator/test_runner/src/pause_bridge.rs
- orchestrator/test_runner/src/relay_market.rs
- orchestrator/test_runner/src/utils.rs
This patch replaces a poorly specified utility function that we used in
our Rust test environment to find gravity coins in test account
balances.
Since Contact did not implement get_balance() but instead only
get_balances() we would iterate over all tokens to find the one we where
interested in. Furthermore we would only check the prefix rather than
the full exact token name.
Removing this behavior should improve test accuracy and also provide a
minor complexity reduction.
> Use contact get_balance

- tests/container-scripts/reload-code.sh
This message would have saved me a lot of time when trying to understand why Docker was not running after start-chains.sh and would be helpful to others.
@ChristianBorst relevant to our integration tests discussion
> Helpful log message start-chains.sh

- module/x/gravity/abci.go
- module/x/gravity/abci_test.go
- module/x/gravity/handler_test.go
- module/x/gravity/keeper/grpc_query.go
- module/x/gravity/keeper/keeper_test.go
- module/x/gravity/keeper/keeper_valset.go
- module/x/gravity/keeper/querier.go
- module/x/gravity/keeper/querier_test.go
- module/x/gravity/types/errors.go
Handles a case for simulations where there are no bonded validators
Closes #35
> Fix endblock panic for simulations where there are no bonded validators

- module/x/gravity/client/cli/tx.go
- module/x/gravity/keeper/governance_proposals.go
A recent commit "register proposal types for the cli" caused the gravity
node to panic on startup due to double registration of proposal types.
Being overconfident that it was a simple fixed I pushed this straight to
master and broke the tests there.
This patch fixes the issue, which somehow invovles App.go calling all
the CLI command code and duplicating the proposal registration. We need
to register proposals in the CLI for the case where we are not running a
full node and App.go does not register the proposal type. The ultimate
soltuion is a check to prevent double registration.
> Fix double call of RegisterProposalTypes

- module/app/app.go
We made an effort in app.go to initialize structs and then use
references to those structs in the gravity app. I changed the struct
initialization to ensure we have no nil values, removed use of
app.struct in favor of the raw struct value use, and added some missing
authz initialization.
> Update app.go to have better consistency

- module/x/gravity/keeper/msg_server.go
I noticed this check for duplicate delegate keys might not be correct, it compares both EthAddress and Orchestrator with addr.GetAddress which is ethereum address.
> Fix SetOrchestratorAddress duplicate key check

- module/x/gravity/keeper/grpc_query.go
- module/x/gravity/keeper/keeper_valset.go
- module/x/gravity/types/key.go
The function GetValsetConfirms breaks when the validator set nonce
exceeds the value of 128. This is because types/key.go was modified to
use strings for indexing but this function was not modified to perform
the same conversion when deciding it's prefix range.
This has the unfortunate effect of halting the chain, for validator sets
greater than 128 becuase the confirms will not be successfuly located in
abci.go when valset slashing is performed. Resutling in slashing of all
the validators at the same block.
This patch corrects the issue for GetValsetConfirm by stringifying the
nonce in the same way as types/key.go
But the existance of this issue highlights a larger need to further
restructure key.go to provide prefixed keys so that modifications are
more localized and the addition of …
> Fix ValsetConfirm iteration

- .github/workflows/automated-release.yml
- orchestrator/.cargo/config
This patch adds mac support for the gbt binary in the automated release
script. This rounds out platform support across all three major
platforms for both the gravity and gbt cli tools.
> Add gbt-mac build to automated release

- tests/container-scripts/run-eth.sh
Since we're using our development environment as a mini testnet this is
required so that frontends can make requests to the server without
violating cors.
This may have some security implications but only when the test environment is run on a machine that has no firewall, considering the normal case for this is a developer who needs more remote processing power exposing the endpoints seems like a good thing to ease development.
> Modfiy geth config to allow remote requests

- module/x/gravity/abci.go
- module/x/gravity/abci_test.go
- module/x/gravity/keeper/batch.go
- module/x/gravity/keeper/batch_test.go
- module/x/gravity/keeper/keeper_batch.go
- module/x/gravity/keeper/keeper_valset.go
Fix for issue #41 includes:
- Deleting validator set confirmations from the store together with their validator sets in pruneValsets().
- Deleting batch confirmations from the store together with their batches in OutgoingTxBatchExecuted() and CancelOutgoingTXBatch()
> ValSet/Batch confirmations not removed from the store #41- fix

- orchestrator/Cargo.lock
- orchestrator/gbt/Cargo.toml
New in this version is a max_gas check that protects against strange
cosmos-sdk behavior when a single transaction exceeds the maximum
allowed gas in a block.
> Bump for Deep Space v1.8.8 

- module/x/gravity/client/cli/query.go
- module/x/gravity/client/cli/tx.go
- orchestrator/orchestrator/src/main_loop.rs
Fix for issue #68 
I also fixed incorrect orchestrator logs for valset, batch and logic calls.
And help message when using gravity q gravity pending-batch-request/pending-valset-requests (now shows "orchestrator address" instead of "validator address").
> Gravity cli panics when calling send-to-eth #68-fix

- module/proto/gravity/v1/attestation.proto
- module/proto/gravity/v1/batch.proto
- module/proto/gravity/v1/msgs.proto
- module/proto/gravity/v1/pool.proto
- module/x/gravity/abci.go
- module/x/gravity/keeper/attestation.go
- module/x/gravity/keeper/attestation_handler.go
- module/x/gravity/keeper/batch.go
- module/x/gravity/keeper/keeper_logic_call.go
- module/x/gravity/keeper/keeper_valset.go
- module/x/gravity/keeper/msg_server.go
- module/x/gravity/keeper/pool.go
- module/x/gravity/types/attestation.pb.go
- module/x/gravity/types/batch.pb.go
- module/x/gravity/types/events.go
- module/x/gravity/types/msgs.pb.go
- module/x/gravity/types/pool.pb.go
fix issue #69 
> * [x]  Create event types for all our existing events, look at cosmos-sdk modules for examples, they should be a proto `message` definition
> * [x]  Refactor existing events everywhere `EmitEvent()` is called in the gravity module
partial:
> * [ ]  Consider refactoring the event type strings, e.g. we have mixed usage of MsgSendToCosmos and BridgeDeposit, making consistent types will go a long way for reducing questions from frontend integrators
> fix issue #69 EmitEvent() -> EmitTypedEvent()

- module/app/ante.go
- module/app/app.go
This PR performs a little trick to make sure we keep up with any cosmos-sdk antehandler changes while still preserving our ability to chain additional antedecorators after the cosmos-sdk antehandler runs. This way we don't need to artisanally prune a thoroughly confusing chain of antedecorators by hand, we can just upgrade the SDK with slightly less headache.
> First AnteHandler PR: add ibc-go antedecorator to sdk antehandler

- module/x/gravity/abci.go
- module/x/gravity/abci_test.go
- module/x/gravity/keeper/keeper_delegate_key.go
- module/x/gravity/keeper/msg_server.go
This PR addresses 2 issues:
~- ETH addresses are now required to be checksummed (these means all ETH addresses). This might be an issue for already running chains if relayers don't send all of the addresses in the compliant format.~
~@jkilpatr this might be a change too drastic if there are any eth addresses in the store that aren't well-formatted, I think we are good on Umee's side because we use geth's common package for addresses. This might also break some of your shell tests~
- Accept confirms only from bonded or unbonding validators
- Don't panic when prepping the confirms for slashing if it can't find a validator
These last 2 are in the first 2 commits if you want to check them with less background noise.
EDIT: Removed Eth address related changes to make a better fix in a separate …
> fix: accept confirms only from bonded or unbonding validators

- module/x/gravity/client/cli/query.go
Add a missing CLI command for querying params (`$ <appd> q gravity params`)
> feature: add missing CLI command for params

- module/x/gravity/keeper/pool.go
- module/x/gravity/keeper/pool_test.go
Now we use `ERC20ToDenomLookup` to look for the right denom to refund instead of `.GravityCoin()`.
Please double-check if this is enough to solve the issue or if we need to add something else.
Closes #107
> fix: Refund now looks for denom before sending tokens

- module/cmd/gravity/cmd/root.go
Cmd registration happens automatically when passing an AppModule to
Gravity's ModuleManager constructor, this explicit registration in
txCommand() is unnecessary and confusing.
> Fix vesting cli double-register

- module/x/gravity/keeper/attestation.go
- module/x/gravity/types/errors.go
- orchestrator/orchestrator/src/main_loop.rs
- orchestrator/test_runner/src/unhalt_bridge.rs
The change in this PR solves the problem of submitting claims with unordered event nonce. This can happen if  the last_checked_event on the orchestrator side is set to 'n' and in the next iteration when check_for_events is called, there is event with the nonce 'n+1' that should be submitted but in the meantime the governance vote reset the last event nonce by the validator to 'n-1' on the chain side. 
check_for_events will try to submit event with nonce 'n+1' to the chain where last submitted nonce is set to 'n-1' and that will fail. Before this fix there was no recovery from this scenario because the last_checked_block was reset only if check_for_events returns successful result and the last event nonce on orchestrator was greater than the last event nonce on the chain side.
This check …
> Attestation order

- orchestrator/Cargo.lock
This patch regenerates the Cargo.lock for gbt to resolve a vulnerability
reported to Cargo Audit.
> Bump Rust dependencies to resolve Cargo Audit warnings

- orchestrator/gbt/src/client/deploy_erc20_representation.rs
Previously when deploying an erc20 representation gbt would only wait
for 100 seconds before declaring the attempt a failure.
Since the claims process requires 2/3 of the voting power worth of
validators to successfully send a tx this is not long enough in a
production environment and would result in a spurious error.
This patch dramatically improves the error behavior by both waiting
longer and inspecting the recent attestation history to determine what
may be wrong and present a message to the user that is accurate and not
confusing.
During development I noticed that the attestion query filtering features
do not seem to be working properly, I've opened issue #133 for this.
> Improve gbt client deploy-erc20 error behavior

- .github/workflows/integration-tests.yml
- tests/all-up-test.sh
- tests/container-scripts/all-up-test-internal.sh
- tests/dockerfile/Dockerfile
This patch adds a new env flag NO_BUILD_IMAGE which prevents building an
image when running the all-up-test.sh this should dramatically reduce
the runtime of our integration tests by only having the happy path geth
test build the docker container.
Another minor fix made here is to move the solidity contract building into
the container and out of the all-up-test-internal.sh so that it can also
only be run once.
Finally we build the test runner specifically rather than the entire orchestrator folder. Reducing the amount of re-building that goes on each image run.
> Optimizations for integration test runtime

- tests/container-scripts/run-testnet.sh
- tests/start-chains.sh
Hey there I changed the test scripts so everything can be accessed externally. And cors is enabled. This allows for easier development of gravity tools.
> Make test setup accessible externally

- .github/workflows/integration-tests.yml
- module/app/upgrades/register.go
- module/app/upgrades/v2/constants.go
- module/app/upgrades/v2/handler.go
- orchestrator/cosmos_gravity/src/query.rs
- orchestrator/test_runner/src/bootstrapping.rs
- orchestrator/test_runner/src/upgrade.rs
- tests/container-scripts/upgrade-test-internal.sh
While not necessary for the upgrade to process correctly, this
mercury2.0 upgrade handler will show to validators that the upgrade has
been completed successfully, and solve the issue of performing the
upgrade with `--unsafe-skip-upgrades` when no handler is registered.
> Add no-op mercury2.0 upgrade handler

- docs/developer/environment-setup.md
- orchestrator/test_runner/src/main.rs
Right now if you want to do testing or integration work locally you run
'start chains' and then you run a specific test case. This patch adds a
dummy test case RUN_ORCH_ONLY which starts up the orchestrators and ibc
relayer only and leaves you free to run external tests and send
transactions with the bridge acting as normal.
This is useful for integrators who are testing locally.
> Add test runner case for only running orch

- orchestrator/test_runner/src/main.rs
- orchestrator/test_runner/src/orch_only.rs
This PR adds a fix on top of PR #172 which was meant to run the orchestrators without running any particular test case. The fix is simply to run the `start_orchestrators` furnction.
Tested this by running the test_runner locally with `./tests/run-tests.sh RUN_ORCH_ONLY` and then manually bridging funds from the Ethereum chain to the Cosmos chain.
> Fix RUN_ORCH_ONLY test_runner

- module/x/gravity/keeper/msg_server.go
The current code would eventually panic 
```
err = nil
sdkerrors.Wrap(err, "destination address is invalid or blacklisted") = nil
```
> Fix error returned when recipient is in the blacklist

- .github/workflows/automated-release.yml
- orchestrator/cosmos_gravity/src/send.rs
- orchestrator/gravity_proto/src/prost/gravity.v1.rs
- orchestrator/gravity_utils/src/types/config.rs
- orchestrator/gravity_utils/src/types/ethereum_events.rs
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
As an optimization strategy the orchestrator bundles as many oracle
submissions as possible into a single message. Normally this works
great but recently a validator that has not been active for some time
unajailed nad has found their orchestrator unable to catch up because it
can not submit the thousands of events as a single message.
This patch adds a constant cap to the number of oracle events in a
single transaction which would prevent this scenario. I'm not totally happy with this patch as the event processing code is badly in need of some generics. Last time I tried this the traits proved to be too frustrating to untangle but I know it can be done better. 
Fixes #188
> Oracle bundling fix

- module/x/gravity/keeper/msg_server.go
This change was only required for a consensus compatible upgrade, to
avoid ticking the gas counter by accessing the store. Now that it's no
longer a consideration it should be re-simplified.
Also removes a capital from the log message as for some reason that triggers a lint.
> Remove gas hack for batch msg check

- orchestrator/Cargo.lock
- orchestrator/cosmos_gravity/Cargo.toml
- orchestrator/ethereum_gravity/Cargo.toml
- orchestrator/gbt/Cargo.toml
- orchestrator/gravity_proto/Cargo.toml
- orchestrator/gravity_utils/Cargo.toml
- orchestrator/orchestrator/Cargo.toml
- orchestrator/relayer/Cargo.toml
- orchestrator/test_runner/Cargo.toml
This patch upgrades Deep Space and Clarity, mainly revolving around
upgrades in those crates to the secp256k1 library and resolving some
ethermint keys cleanup in Deep Space
> Upgrade Deep Space, Clarity

- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/orchestrator/src/oracle_resync.rs
While oracle resync has a very reasonable amount of blocks being requested the the actual oracle once it's 'caught up' to the present moment tries to get every block from the last oracle message for that validator up to the present in a single set of queries. This simply isn't pracitcal beyond a certain point.
This patch modifies the oracle check for events code to match the oracle resync code and only check for 5k ethereum blocks at a time. Other recent fixes for behind validators ensure that if millions of events are found within those 5k blocks they are submitted in reasonable batches of 1k oracle messages per transaction.
> Fix oracle syncing for very old event nonces

- orchestrator/Cargo.lock
- orchestrator/gbt/Cargo.toml
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/orchestrator/src/main_loop.rs
This patch *is not* a complete ethereum proof of stake update for the Orchestrator. It only removes the merge countdown and sets a 64 block delay for assumed finality.
Previously we waited 13 blocks for finality given known probabilities of proof of work re-orgs but there was no way to really 'know' when somthing was final.
ETH2 does provide actual finality. The problem is it takes a while and is difficult to query. Mapping consensus layer slots to execution layer blocks is a complex process best left to an API query which does not seem to exist, at least in any obvious form.
This patch uses a 64 block delay which is in all probability safer than our previous proof of work delay, but does not check for actual ETH2 finality, we will update GBT to do this in the future once we have a 100% …
> Remove merge countdown, modify block delay

- orchestrator/Cargo.lock
- orchestrator/gbt/Cargo.toml
- orchestrator/gbt/src/args.rs
- orchestrator/gbt/src/client/cosmos_to_eth.rs
- orchestrator/gbt/src/keys/mod.rs
- orchestrator/gbt/src/main.rs
Users whose funds are "stuck" because of an IBC Auto Forward failure can use recover-funds to send tokens from the Ethermint-style Gravity address to another Gravity address or to Ethereum.
> Add gbt keys recover-funds command

- module/app/ante/min_commission.go
- module/x/gravity/keeper/invariants.go
**MaxRate check:** While this check should be redundant due to upstream ValidateBasic checks, it is worth checking assumptions in the AnteHandler so that strange behavior is caught early
**Transfer module balance":** A mistake was made when writing the PendingIbcAutoForward invariant checks, the transfer module does not get custody of funds until the pending IBC Auto forward is executed, so the invariant is unable to make any claims about balances here. Adding a check to the gravity account's balance would inevitably cause an unnecessary chain halt.
> Add MaxRate check to MinCommissionDecorator, Remove errant transfer module balance checks in Invariant

- module/x/gravity/types/msgs.go
- module/x/gravity/types/msgs_test.go
- module/x/gravity/types/test_utils.go
The SetOrchestrator method was added to EthereumClaim to make testing MUCH easier, reduces a lot of testing bloat this way.
> Fix logic call ClaimHash, add ClaimHash tests

- .github/workflows/integration-tests.yml
- docs/design/oracle.md
- module/app/upgrades/orion/README.md
- module/app/upgrades/orion/constants.go
- module/app/upgrades/orion/handler.go
- module/app/upgrades/register.go
- module/x/gravity/abci.go
- module/x/gravity/types/msgs.go
- orchestrator/Cargo.lock
- orchestrator/Cargo.toml
- orchestrator/gbt/Cargo.toml
- orchestrator/gravity_proto/src/ethereum_claim.rs
- orchestrator/gravity_utils/src/types/valsets.rs
- orchestrator/test_runner/src/upgrade.rs
- tests/run-all-tests.sh
This is an alternate upgrade path for the Orion upgrade in response to last minute issues found with the balance checking logic.
This change does not introduce cross bridge balance checking or any of it's code, the current code will be rebased on top of this branch and another upgrade can be performed with the finished check. This upgrade, if chosen by the validators would only contains the cosmos-sdk update, gbt deps updates, and move tx fee collection for gravity into the message handler.
> Orion without balance checking

- orchestrator/Cargo.lock
- orchestrator/gbt/Cargo.toml
- orchestrator/gbt/src/args.rs
- orchestrator/gbt/src/client/mod.rs
- orchestrator/gbt/src/client/spot_relay.rs
- orchestrator/gbt/src/main.rs
This patch adds a new user-friendly spot relay command. This command is
intended for potential relayers who want to relay a specific batch or
token type on command without fussing with the main relayer code and
it's profitability estimates.
> Add spot relayer command

- orchestrator/Cargo.lock
- orchestrator/gbt/Cargo.toml
- orchestrator/gbt/src/client/spot_relay.rs
Previously the spot relay command used a recent valset simply for ease.
But as it turns out it's not that complicated at all to lookup the
correct valset.
Furthermore we where trying to query signatures we looked up the wrong
ones, using the gravity address rather than the target token address
> Fixes for spot relay

- orchestrator/gbt/src/client/deploy_erc20_representation.rs
This function was making a pretty obvious error just optimistically interpreting the txid of the deployment tx as the contract that would result from the tx being successful. This is a simple fix that removes that check rather than actually developing a method to get the deployed contract.
> Fix: erc20 representation deployment

- module/Makefile
With Make 4.3+, the empty whitespace does not seem to work as originally intended. This causes build tags to be `"netgo ledger,"` on Ubuntu 22.04 and other systems that include the newer Make version. The build tags were intended as `"netgo,ledger"` which can be observed on Make 4.2 (shipped with Ubuntu 20.04).
This change swaps out the `+=` use in favor of an explicit `:=`.
Ref: https://www.gnu.org/software/make/manual/html_node/Appending.html
Upstream reference: cosmos/gaia#2017
This can be observed either via API or directly via CLI:
```text
$ gravityd version --long 2>&1 | head -n5
name: gravity
server_name: gravity
version: v1.8.1
commit: ea35ec51aa921f60bb0911bd5482f12a438241e0
build_tags: netgo ledger,
```
> Consistently generate build tags on Make 4.3+

- .build.sh
- module/Makefile
- tests/build-container.sh
- tests/dockerfile/Dockerfile
Previously binary protections where only available in the 'make build-reproducible' flow. There was an attempt to enable them for 'make install' but checking of the binaries showed that it was not effective.
This patch ensures that any time a go binary is built binary security functions are enabled.
Here are outputs from checksec for binaries with and without ledger support respectively.
```
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      No canary found   NX enabled    PIE enabled     No RPATH   No RUNPATH   85747 Symbols	  Yes	5		12		/home/justin/go/bin/gravity
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full …
```
> Enable binary protections for 'make install'

- .github/workflows/rust.yml
- orchestrator/cackle.toml
THis is a project to help make Rust supply chain attacks harder by specifying specific permissions for dependencies and allowing them individually.
https://davidlattimore.github.io/making-supply-chain-attacks-harder.html
I'm impressed by how easy the setup process was and while it doesn't verify that no supply chain attacks exist, and is possible to circumvent it will at least prevent the silent addition of a permission grabbing dependency.
> Add cargo ACL

- orchestrator/cosmos_gravity/src/query.rs
This patch reduces the limit in the get_attestations function, while this function is only used in tests in the main gravity repo it is used by the gravity info server to determine when transactions are being finalized.
The 1000 attestation limit is too large and runs into response size errors.
> Reduce get_attestations() limit

- module/x/gravity/client/cli/tx.go
These error messages where insufficiently descriptive and confusing to some users.
> Improve ibc-metadata proposal error messages

- .github/workflows/integration-tests.yml
- .github/workflows/rust.yml
- orchestrator/Cargo.lock
- orchestrator/test_runner/src/bootstrapping.rs
- orchestrator/test_runner/src/main.rs
- solidity/contract-deployer.ts
- tests/all-up-test-ci.sh
- tests/container-scripts/all-up-test-internal.sh
- tests/container-scripts/integration-tests.sh
- tests/container-scripts/run-eth.sh
- tests/container-scripts/run-testnet.sh
This commit modifies the CI test environment to run directly in github actions rather than running inside a container like it would in the local test flow.
This makes it much eaiser to cache build artifacts and resolves issues with github actions no longer allowing enough cache space to make the docker layer cache strategy useful.
> Run CI tests directly in Github actions

- module/x/gravity/client/cli/tx.go
The Go cli always prepended 'gravity' to all inputs in order to format a 0x eth token address into a gravity0x voucher address for the caller. This creates issues when trying to request a cosmos originated token starting with ibc/hash.
This patch adds a simple check that will ensure the denom starts with 0x before making any chnages, allowing users to pass in ibc/hash values, or even gravity0x voucher strings as valid inputs.
> Fix Go cli back requests for gravity originated tokens

- module/x/gravity/client/cli/tx.go
This is a minor improvement for the gravity tx gravity request-batch cli command. Previously it was only possible to use this for Ethereum originated tokens, now it should work in general.
> Improve denom prefix handling for batch requests

- orchestrator/jsonrpc_server/src/server.rs
Rabby wallet makes an eth_chainId request without the unused "params" field in the request body, which breaks Rabby EIP-712 usage with Gravity since the necessary configuration cannot be made. By migrating that field to be an Optional<_> we enable broader wallet integrations.
> Fix JSONRPC server for Rabby wallet users
