Gravity-Bridge/Gravity-Bridge

module/app/app.go
Added the authorization module initialization to app.go.
Used both [simd's](https://github.com/cosmos/cosmos-sdk/blob/v0.44.5/simapp/app.go) and [osmosis'](https://github.com/osmosis-labs/osmosis/blob/v6.0.0/app/app.go) configurations as inspiration for how to fully initialize x/authz.
=> Add x/authz module - Wait for cosmos-sdk update v0.44.5

orchestrator/Cargo.lock, orchestrator/metrics_exporter/Cargo.toml, orchestrator/metrics_exporter/src/metrics_exporter.rs, orchestrator/orchestrator/src/main_loop.rs, orchestrator/orchestrator/src/oracle_resync.rs
- typos fix
- latest_eth_block gauge
- last_checked_event gauge
=> Metrics exporter 0.1.1

orchestrator/test_runner/src/unhalt_bridge.rs
This patch replaces a highly specific function used in the unahlt bridge
test to determine if the governance proposal has passed with the generic
check we use for the airdrop and ibc metadata proposal tests.
In general we're trying to make this test more reliable in ci
=> More reliable unahlt bridge

orchestrator/Cargo.lock, orchestrator/gbt/Cargo.toml, orchestrator/gbt/src/config.rs, orchestrator/gbt/src/default-config.toml, orchestrator/gbt/src/utils.rs, orchestrator/gravity_utils/src/types/config.rs, orchestrator/relayer/src/batch_relaying.rs, orchestrator/relayer/src/valset_relaying.rs, orchestrator/test_runner/src/utils.rs
This pr adds margin parameters to the GBT relayer config. Currently blocked on toml really not liking struct enums.
=> Relayer Margin

solidity/contract-deployer.ts
This patch adds retry logic for the contract-deployer ABCI calls, in
some cases the Gravity nodes do not start until a after the Ethereum
node has successfully been running for some time. This race condition
results in a failure of the test that could hopefully be resolved by
waiting some more.
It's hard to tell how much we just need to wait or if the Cosmos nodes
are crashing behind the scenes, this timeout will at least remove the
possibility of a race condition.
=> Add retry logic for contract-deployer ABCI

module/x/gravity/abci_test.go, module/x/gravity/keeper/batch.go, module/x/gravity/keeper/batch_test.go, module/x/gravity/keeper/pool.go, module/x/gravity/keeper/querier_test.go, module/x/gravity/types/validation.go
=> Transactions with blacklisted eth receivers are included in a batch profitability comparison #40 fix

module/x/gravity/keeper/invariants.go
The module balance invariant was unaware of cosmos originated assets
sticking around while bridged to ethereum, and was also unaware of an
issue tracking cosmos originated assets with no erc20 representation.
=> Fix module balance invariant

module/x/gravity/keeper/grpc_query.go, module/x/gravity/keeper/keeper.go, module/x/gravity/keeper/keeper_batch.go, module/x/gravity/keeper/keeper_logic_call.go, module/x/gravity/keeper/keeper_valset.go, module/x/gravity/types/key.go
#61 if I understood correctly.
=> prefix functions key.go reference issue #61

module/app/ante.go, module/app/app.go
The folks over at Juno added a really nice Minimum Validator Commission feature originally taken from Stargaze and further improved upon in a few ways, this PR adds that feature to Gravity.
Edit: Attribution is now part of the commit as well
=> Second antehandler PR: Add MinCommissionDecorator from the Juno project

module/x/gravity/abci_test.go, module/x/gravity/cosmos-originated_test.go, module/x/gravity/handler_test.go, module/x/gravity/keeper/attestation_test.go, module/x/gravity/keeper/batch_test.go, module/x/gravity/keeper/evidence_test.go, module/x/gravity/keeper/genesis_test.go, module/x/gravity/keeper/governance_proposals_test.go, module/x/gravity/keeper/invariants.go, module/x/gravity/keeper/invariants_test.go, module/x/gravity/keeper/keeper_test.go, module/x/gravity/keeper/pool_test.go, module/x/gravity/keeper/querier_test.go, module/x/gravity/keeper/test_common.go
Other additions: Fixed a nil pointer deref in the module-balance invariant; Improved readability of the module-balance invariant
=> Assert invariants at the end of every unit test

module/x/gravity/abci_test.go, module/x/gravity/keeper/attestation.go, module/x/gravity/keeper/attestation_test.go, module/x/gravity/keeper/batch_test.go, module/x/gravity/keeper/keeper_test.go, module/x/gravity/keeper/keeper_valset_test.go
Added more unit tests and improved some existing ones for keeper methods.
=> Improved unit tests for keeper functions #62

orchestrator/Cargo.lock, orchestrator/cosmos_gravity/Cargo.toml, orchestrator/cosmos_gravity/src/query.rs, orchestrator/ethereum_gravity/Cargo.toml, orchestrator/gbt/Cargo.toml, orchestrator/gravity_proto/Cargo.toml, orchestrator/gravity_proto/src/prost/gravity.v1.rs, orchestrator/gravity_utils/Cargo.toml, orchestrator/orchestrator/Cargo.toml, orchestrator/relayer/Cargo.toml, orchestrator/test_runner/Cargo.toml
This pr updates the deep space library with the latest cosmos protos and re-regenerates the rust protos, which are a little stale after recent chagnes to attestation querying.
=> Update deep space

module/.golangci.yml, module/cmd/gravity/cmd/eth_keys.go, module/cmd/gravity/cmd/genaccounts.go, module/cmd/gravity/cmd/gentx.go, module/cmd/gravity/cmd/migrate.go, module/cmd/gravity/cmd/testnet.go
This lint is rather large and nature and needs to be heavily segmented in order to prevent erroneous changes from creeping in.
=> Exhaustive errcheck code review first batch in a series of lints

orchestrator/test_runner/src/airdrop_proposal.rs
In order to pack as many recipients as possible into the airdrop
proposal transaction each users amount is limited to u64 max, while this
would be impratical for Ethereum based tokens it's completely reasonable
for CosmosSDK tokens with 6 decimals of precision.
As the final step of the airdrop proposal integration test we would try
to generate an airdrop proposal which spends more than the tokens
remaining in the community pool. This would sometimes cause the test to
lockup trying to generate an invalid proposal when it was simply not
possible.
If the amount of tokens remaining in the community pool is greater than
the maximum aridrop size times u64 max the function
generate_invalid_accounts_and_amounts would continue to run forever.
This commit adds a few unit tests that ensure …
=> Keep airdrop integration test from stalling

module/x/gravity/types/validation.go
=> fix: remove power check

docs/design/messages.md, docs/developer/environment-setup.md, module/x/gravity/keeper/attestation.go, module/x/gravity/keeper/governance_proposals.go, module/x/gravity/keeper/keeper.go, module/x/gravity/module.go, module/x/gravity/types/abi_json.go, module/x/gravity/types/ethereum.go, module/x/gravity/types/ethereum_signer.go, module/x/gravity/types/key.go, module/x/gravity/types/validation.go, solidity/contracts/contract-explanation.md
=> Mismatch percentage of required voting power defined in document

orchestrator/Cargo.lock, orchestrator/ethereum_gravity/src/logic_call.rs, orchestrator/ethereum_gravity/src/submit_batch.rs, orchestrator/ethereum_gravity/src/valset_update.rs, orchestrator/gravity_utils/Cargo.toml, orchestrator/gravity_utils/src/prices.rs, orchestrator/gravity_utils/src/types/batches.rs, orchestrator/relayer/src/batch_relaying.rs, orchestrator/relayer/src/logic_call_relaying.rs, orchestrator/relayer/src/request_batches.rs, orchestrator/relayer/src/valset_relaying.rs, tests/dockerfile/Dockerfile
picking up from here https://github.com/Gravity-Bridge/Gravity-Bridge/pull/165
=> Relayer price oracle expansions and improvements

.github/workflows/integration-tests.yml
This really speeds up build times when it works, this pr is for testing and resolving any remaining issues here.
=> Restore docker caching for CI builds

module/x/gravity/keeper/attestation.go
This patch adds rollback protection for ethereum block heights, as well
as the global event nonce counter.
Individual event nonce counters can be rolled backwards by the unhalt
bridge governance proposal, so these are unchanged.
Rolling back the Ethereum block height indicates at the very least that
a fork is in play and that we have already taken into account state from
a different fork, at which point manual intervention is required to
reconcile bridge state.
=> Attestation rollback protection

module/x/icaauth/ibc_module.go
=> (ica) Remove OnAcknowledgementPacket response handling logic #210

orchestrator/gravity_proto/src/lib.rs, orchestrator/gravity_proto/src/prost/gravity.v1.rs, orchestrator/gravity_proto/src/prost/icaauth.v1.rs, orchestrator/proto_build/src/main.rs, orchestrator/test_runner/src/ica.rs
=> (ica) Split off the ICA code into its own prost module #213

module/x/gravity/client/cli/tx.go
This patch fixes a logic issue with the denom-metadata checks, specifically the code was well prepared for a specific allowed edge case, changing the metadata of a token before an erc20 representation has been deployed.
But in trying to support this edge case the code ran into several issues around tokens that have not yet had any metadata deployed, namely that the queries used returned nil and this went unchecked.
This patch modifies the behavior to not support modifying metadata denoms which already have it set even though this is just client side verification and the tx may actually be accepted by the chain.
The primary reason for this reduction in functionality is that we need exceptionally clear error messages for this functionality since submitters are often confused and using ibc …
=> Fixup denom-metadata preflight checks

module/cmd/gravity/cmd/root.go
In order to quickly halt the chain if an invariant ever breaks, we add a random prime between 2 and 199 as the invariant check period on startup for nodes which have not already provided an invariant check period.
=> Add a random prime invariant check period on startup

.github/workflows/integration-tests.yml, orchestrator/Cargo.lock, orchestrator/gbt/Cargo.toml, orchestrator/test_runner/src/happy_path_v2.rs, orchestrator/test_runner/src/main.rs, orchestrator/test_runner/src/utils.rs
This just tests the erc20 representation flow with the native token specifically to see if any errors are triggered.
=> Add happy path_v2 variant for the native token

tests/all-up-test.sh, tests/build-container.sh, tests/manual-upgrade-test.sh, tests/run-upgrade-test.sh, tests/start-chains.sh
$ sysctl -a | grep brand
machdep.cpu.brand_string: Apple M2 Pro
=> Update container to support for Apple silicon

.github/workflows/integration-tests.yml, module/app/app.go, module/app/upgrades/apollo/README.md, module/app/upgrades/apollo/constants.go, module/app/upgrades/apollo/handler.go, module/app/upgrades/register.go, module/x/auction/client/cli/query.go, module/x/gravity/keeper/migrations.go, module/x/gravity/migrations/v4/params.go, module/x/gravity/migrations/v5/migrate.go, module/x/gravity/module.go, orchestrator/Cargo.lock, orchestrator/cosmos_gravity/src/proposals.rs, orchestrator/test_runner/Cargo.toml, orchestrator/test_runner/src/auction.rs, orchestrator/test_runner/src/bootstrapping.rs, orchestrator/test_runner/src/eip_712.rs, orchestrator/test_runner/src/main.rs, orchestrator/test_runner/src/upgrade.rs, tests/assets/ibc-relayer-config.toml, tests/container-scripts/setup-validators.sh, tests/dockerfile/Dockerfile
=> The Apollo Upgrade

orchestrator/Cargo.lock, orchestrator/metrics_exporter/Cargo.toml
I just updated tiny_http in my copy of this repo
=> Update metrics exporter

module/x/auction/abci.go, module/x/auction/keeper/msg_server.go
This PR is expected to have a failure in the upgrade test due to default auction module Params. See PR #292 for the upgrade test results.
=> Auction Endblocker supply integrity check

module/x/auction/client/cli/query.go, module/x/auction/client/cli/tx_bid.go
=> Add helpful auction module client errors
